package se.deogun.aes.api;

public enum RejectReason {
    NO_SECURE_RANDOM_ALGORITHM_AVAILABLE_ON_THIS_SYSTEM,
    ALGORITHM_NOT_SUPPORTING_AAD,
    UNABLE_TO_DECRYPT_DATA,
    UNABLE_TO_ENCRYPT_DATA,
    GCM_NOT_AVAILABLE_ON_THIS_SYSTEM,
    GCM_INVALID_KEY,
    GCM_INVALID_PARAMETERS,
    GCM_INVALID_TAG,
    CBC_INVALID_KEY,
    CBC_NOT_AVAILABLE_ON_THIS_SYSTEM,
    CBC_INVALID_PARAMETERS;
}
