package se.deogun.aes.modes;

public enum AESRejectReason {
    NO_SECURE_RANDOM_ALGORITHM_AVAILABLE_ON_THIS_SYSTEM,
    UNABLE_TO_DECRYPT_DATA,
    UNABLE_TO_ENCRYPT_DATA,
    GCM_NOT_AVAILABLE_ON_THIS_SYSTEM,
    GCM_INVALID_KEY,
    GCM_INVALID_PARAMETERS,
    GCM_INVALID_TAG
}
