package se.deogun.aes.modes;

public enum AESRejectReason {
    AES_GCM_NOT_AVAILABLE_ON_THIS_SYSTEM,
    UNABLE_TO_DECRYPT_DATA,
    UNABLE_TO_ENCRYPT_DATA,
    INVALID_GCM_KEY,
    INVALID_GCM_PARAMETERS,
    INVALID_GCM_TAG,
    DECRYPTION_LIMIT_EXCEEDED,
    ENCRYPTION_LIMIT_EXCEEDED
}
